version: "3.7"
services:
  django-db:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=filesenddb"
      - "MYSQL_USER=filesenduser"
      - "MYSQL_PASSWORD=filesendpassword"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql