# Generated by Django 4.1.2 on 2023-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
