# Generated by Django 4.1.2 on 2023-01-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
