# Generated by Django 4.1.2 on 2023-01-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
