# Generated by Django 4.1.2 on 2023-02-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
